---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-compute-kit
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: "Deploy nova and neutron"
  sequenced: False
  chart_group:
    - nova
    - neutron
