---
schema: promenade/Docker/v1
metadata:
  schema: metadata/Document/v1
  name: docker-global
  labels:
    promenade: enabled
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  config:
    insecure-registries:
      - artifacts-aic.atlantafoundry.com
    live-restore: true
    max-concurrent-downloads: 10
    storage-driver: overlay2
