---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-storage-provisioner
  replacement: true
  labels:
    name: ucp-storage-provisioner
    group: ucp
    service: k8_storage_provisioning
  layeringDefinition:
    abstract: false
    layer: site
    actions:
      - method: merge
        path: .
    parentSelector:
      name: ucp-storage-provisioner
  storagePolicy: cleartext
data:
  description: Kubernetes Storage Provisioner
  sequenced: true
  chart_group:
    - ucp-ceph
    - ucp-ceph-config
    - os-ceph-config
