---
schema: pegleg/SoftwareVersions/v1
metadata:
  schema: metadata/Document/v1
  name: software-versions
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: software-versions
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
# This document is merged with the globals, and is where you can override
# versions to match a patchset, for example. Anything specified in the global
# versions can be overridden, such as chart or image versions.
data:
  charts:
    ucp:
      maas:
        location: https://git.openstack.org/openstack/airship-maas
        reference: refs/changes/53/600253/1
  images:
    ucp:
      maas:
        maas_region: docker.io/sthussey/maas-region-controller:dev
...
